## Deployment playbook goes here.
---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend folder
  template:  
   # src: "files/index.js"
    src: ~/backend
    dest: "~/"    # web"
    remote_src: true
- name: Executing node
  shell: |
    cd ~/
    tar -xzvf artifact.tar.gz -C .
    npm install
    pm2 stop default
    pm2 start npm -- start
   # pm2 start ~/web/index.js -f
   #tar -C backend -xzvf artifact.tar.gz .
