---
- name: remove dependencies that are no longer required
  become: yes
  yum:
    autoremove: yes

- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: extract backend folder into ec2 instance
  unarchive:
    src: "{{playbook_dir}}/files/artifact.tar.gz"
    dest: ~/backend

- name: install npm
  become: true
  shell: |
    cd backend
    npm install
- name: Executing node
  become: true
  shell: |
    cd backend
    pm2 start
    pm2 serve . 3030
     
   # pm2 start npm --start
   # pm2 start npm 
   # pm2 stop default
   


## Deployment playbook goes here.
#---


#- name: "upgrade packages"
  #become: yes
  #yum:
  #  upgrade: yes

#- name: "install dependencies."
 # become: yes
  #yum:
   # name: ["nodejs", "npm"]
    #state: latest
    #update_cache: yes

#- name: "install pm2"
 # become: yes
 # npm:
   # name: pm2
   # global: yes
    #production: yes
    #state: present



#******
#- name: Copy backend folder
 # copy: 
 #   src: "{{playbook_dir}}/files/"
   # dest: "~/web"
  #  remote_src: no
#- name: unzip backend folder
 # shell: |
  #  cd web 
  #  tar -xzvf artifact.tar.gz .
   # ls .




  #pm2 start npm --start
  #-name: extract backend folder into ec2 instance
  #unarchive:
  #src: artifact.tar.gz
  #dest: ~/web


   #pm2 start ~/web/ -f
   # pm2 stop default
   # pm2 start 
   # pm2 start ~/ -f
   # npm install
   # pm2 start npm --start
   # pm2 start ~/web/index.js -f
   #npm i -g pm2
