## Deployment playbook goes here.
---
- name: "update apt packages."
  become: yes
  yum:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  yum:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  yum:
    autoremove: yes

- name: "install dependencies."
  become: yes
  yum:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

#- name: Creates directory
  #file:
    #path: ~/web
    #state: directory

- name: Copy backend folder
  copy: 
    src: "{{playbook_dir}}/files/"
    dest: "~/"
    remote_src: no
- name: unzip backend folder
  shell: |
    cd ~/
    tar -xzvf artifact.tar.gz .
    ls .
- name: Executing node
  shell: |
    cd ~/
    npm install
    pm2 stop default
    pm2 start 




    
   # pm2 start npm --start
   # pm2 start ~/web/index.js -f
