## Deployment playbook goes here.
---
- name: "update apt packages."
  become: yes
  yum:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  yum:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  yum:
    autoremove: yes

- name: "install dependencies."
  become: yes
  yum:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend folder
  copy: 
    src: "{{playbook_dir}}/files/"
    dest: "~/web"
    remote_src: no
- name: unzip backend folder
  shell: |
    cd web 
    tar -xzvf artifact.tar.gz .
    ls .
- name: install npm
  become: true
  shell: |
    cd web
    npm install
- name: Executing node
  become: true
  shell: |
    cd web
    pm2 start
    
   


  #pm2 start npm --start
  #-name: extract backend folder into ec2 instance
  #unarchive:
  #src: artifact.tar.gz
  #dest: ~/web


   #pm2 start ~/web/ -f
   # pm2 stop default
   # pm2 start 
   # pm2 start ~/ -f
   # npm install
   # pm2 start npm --start
   # pm2 start ~/web/index.js -f
   #npm i -g pm2
