version: 2.1


jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: frontend-build-job
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
           # Your code here
  
      - save_cache:
          paths: frontend/node_modules
          key: frontend-build-job

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: backend-build-job
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
          # Your code here
      - save_cache:
          paths: backend/node_modules
          key: backend-build-job
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: frontend-test-job
      - run:
          name: test front-end
          command: |
            cd frontend
            npm install
            npm run test
          # Your code here    
      - save_cache:
          paths: frontend/node_modules
          key: frontend-test-job
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: backend-test-job
      - run:
          name: test back-end
          command: |
            cd frontend
            npm install
            npm run test
          # Your code here      
      - save_cache:
          paths: backend/node_modules
          key: backend-test-job

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: frontend-analyze
      - run:
          name: analyze front-end
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
        # npm install oauth-sign@^0.9.0
            
          # Your code here    
      - save_cache:
          paths: frontend/node_modules
          key: frontend-analyze

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: backend-analyze
      - run:
          name: analyze back-end
          command: |
              cd backend
              npm install 
              npm audit --audit-level=critical
          # npm install oauth-sign@^0.9.0
       
      - save_cache:
          paths: backend/node_modules
          key: backend-analyze
    

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires: 
            - build-backend
      - scan-backend:
          requires:
            - build-backend
      - scan-frontend:
          requires: 
            - build-frontend


