version: 2.1


jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: frontend-build-job
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
           # Your code here
  
      - save_cache:
          paths: frontend/node_modules
          key: frontend-build-job

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: backend-build-job
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
          # Your code here
            
      - save_cache:
          paths: backend/node_modules
          key: backend-build-job

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
          